import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/shared/components/Navbar";
import MainFooter from "@/shared/components/MainFooter";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App00",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-6">
          <Navbar />
          {children}
          <MainFooter />
        </main>
      </body>
    </html>
  );
}
